name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *' # Runs every day at 2am: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

jobs:
  Setup-and-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Trace Server
        run: curl -o trace-compass-server.tar.gz https://download.eclipse.org/tracecompass.incubator/trace-server/rcp/trace-compass-server-latest-linux.gtk.x86_64.tar.gz; tar -xf trace-compass-server.tar.gz
      - name: Start Trace Server
        run: nohup ./trace-compass-server/tracecompass-server&
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 
      - name: Set up virtual environment
        run: python3 -m venv .venv
      - name: Install dependencies
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Run tests
        run: |
          .venv/bin/pytest
